### ISSUE TITLE
CurseForge comments are off

### ISSUE THREAD

**Issue by SHsuperCM** [thraaawn/PipeMaster#1]
Wanted to say that the mod looks really well made and wanted to comment on the icon because I almost missed that mod while scrolling through since it looked like a copy pasted asset from the internet which usually turns me away from mods personally...

**Comment by davenonymous** [comment]
It's a temporary placeholder icon. It's an alpha mod in a very early state.
CurseForge comments are on par with YouTube comments; I have disabled them on purpose.
