### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by brisingraerowing** [thraaawn/PipeMaster#4]
[Crash Log](https://paste.dimdev.org/dehedidapa.mccrash)

No custom files (I was going to add one for XNet, but...)

Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* PipeMaster: 1.0.2-b8

**Comment by brisingraerowing** [comment]
A bit more info: I had started the game to generate the config files, and that worked. I then closed the game, configured almost everything, and created a blockgroup file for XNet (which was empty). I then started the game again, and it crashed. Removing the empty file didn't fix the crash.

**Comment by davenonymous** [comment]
You waited until I released the 1.14 version, didn't you? ;)
What was the last "Loading blockgroups from file:" line in your server log?
Edit: And what is the content of that file?
Btw: XNet has this feature built in, just hold a network cable in your hand...

**Comment by brisingraerowing** [comment]
Ah. I wasn't aware of that. I'll see if I can find the log.

**Comment by brisingraerowing** [comment]
It was trying to load the nonexistent XNet file I had created.

[Log](https://gist.github.com/BrisingrAerowing/6753a895323371a2f782bbea54296377)

**Comment by davenonymous** [comment]
And you are sure the file is really gone and not just empty?
Edit: I mean, it doesn't pull the idea that there is a file named 'xnet.json' out of thin air. There is also no caching anywhere. Check your config file, did you specify xnet in there somewhere?

**Comment by brisingraerowing** [comment]
I had to reboot for an update, and the issue no longer happens. 😕

I think this might be a Win10 issue, as I've had phantom files before with other applications. They did go away after a while, but would gladly open and display their previous content.
